# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 8, 7, 16, 41, 19, 373872, tzinfo=utc)),
        ),
    ]
